# Generated by Django 2.1.7 on 2019-03-31 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190330_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Services')),
                ('the_choices', models.ManyToManyField(to='core.Choices')),
            ],
        ),
        migrations.AddField(
            model_name='appointement',
            name='service_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ServiceType'),
            preserve_default=False,
        ),
    ]
